deps: bump to node 20 to match sentry
getsentry/chartcuterie pull request #138
Opened 2023-12-29 18:50 UTC by JonasBa

Chartcuterie runs on node 16, but sentry builds it with node 20 target which causes wrong core-js polyfills to be applied, which ends up throwing a runtime error.

2023-12-30 19:59 UTC, anonrig approved these changes

2024-01-01 07:19 UTC, scttcper requested changes
My New Year's resolution is to decline

2024-01-01 14:03 UTC, JonasBa commented
@scttcper does this break something :D?

2024-01-01 18:53 UTC, scttcper approved these changes
Nah just wanted a chance to try it. Looks good

2024-01-01 20:13 UTC, JonasBa commented
aight haha :D Thanks for double checking 🥳

2024-01-02 14:27 UTC, merged